cinchy-co/meta-forms-app-experience

src/app/dynamic-forms/cinchy-dynamic-forms.component.ts
Fix creation of child forms based on indirect link to parent table to work with non-numeric key values
=> CIN-08203: Fix creation of child forms based on indirect link

src/app/dynamic-forms/cinchy-dynamic-forms.component.html, src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts
CIN-09512: Pressing enter results in loss of user data,
CIN-09513: Crashes when you enter text in to a link column,
CIN-09562: Values not sorted in linked column pick-list
=> CIN-09512, CIN-09513, CIN-09562 Bug Fix

src/app/dynamic-forms/fields/cinchy-form-link.directive.ts, src/app/dynamic-forms/style/style.scss
Committing changes for CIN-10504
=> CIN-10504: Styling changes to linked column labels

src/app/dynamic-forms/models/cinchy-form.model.ts
- Resolved bug CIN-09751 for saving data
=> CIN-09751: Issue Saving Forms

src/app/dynamic-forms/service/form-helper/form-helper.service.ts
- Resolved child form issue and committed changes.
=> CIN-10592: Date fields in child forms break display layout

src/app/dynamic-forms/cinchy-dynamic-forms.component.ts, src/app/shared/search-dropdown/search-dropdown.component.html, src/app/shared/search-dropdown/search-dropdown.component.ts
- Committed changes for CIN-07656
=> CIN-07656: Drop down doesn't appear if no records exist in destination table

package.json, src/app/dynamic-forms/cinchy-dynamic-forms.module.ts, src/app/dynamic-forms/fields/cinchy-form-calculated.directive.ts, src/app/dynamic-forms/fields/cinchy-form-checkbox.directive.ts, src/app/dynamic-forms/fields/cinchy-form-choice.directive.ts, src/app/dynamic-forms/fields/cinchy-form-datetime.directive.ts, src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts, src/app/dynamic-forms/fields/cinchy-form-multichoice.directive.ts, src/app/dynamic-forms/fields/cinchy-form-number.directive.ts, src/app/dynamic-forms/fields/cinchy-form-textarea.directive.ts, src/app/dynamic-forms/fields/cinchy-form-textbox.directive.ts, src/app/dynamic-forms/style/style.scss, src/app/shared/typeahead/typeahead.component.html, src/styles.scss
- Committing changes for tool tip with ! icon , gray color with customize tooltip text.
=> EXP-00427: Add an "i" icon next to column labels in Form input labels in the Forms view

src/app/dynamic-forms/cinchy-dynamic-forms.component.ts, src/app/dynamic-forms/fields-wrapper/fields-wrapper.component.html, src/app/dynamic-forms/fields-wrapper/fields-wrapper.component.ts, src/app/services/app-state.service.ts
committing changes for EXP- 00422 Meta-Forms loading sections before data
=> EXP- 00422 Meta-Forms loading sections before data

src/app/core/sidenav/sidenav.component.ts
- changed url for back to table view link
=> CIN-1669: Back to table view link works as expected

src/app/dynamic-forms/style/style.scss
committing css changes for font awsome icon
=> EXP-00424: Add field type icons from the data grid view to forms view

package.json, src/app/dynamic-forms/fields/cinchy-form-attachfile.directive.ts, src/app/dynamic-forms/fields/cinchy-form-datetime.directive.ts
committing changes for form icon
=> committing changes for form icon

src/app/dynamic-forms/fields/cinchy-form-checkbox.directive.ts
committing outline changes for checkbox control
=> committing outline changes for checkbox control

src/app/core/sidenav/sidenav.component.ts
- Back to table view link does not work in forms
=> CIN-1669/EXP-00550: Back to table view link does not work in forms

Dockerfile
Adds curl update to resolve curl version vulnerabilities
=> CIN-01686: updating curl version in image base

src/app/dynamic-forms/fields/cinchy-form-calculated.directive.ts, src/app/dynamic-forms/fields/cinchy-form-checkbox.directive.ts, src/app/dynamic-forms/fields/cinchy-form-choice.directive.ts, src/app/dynamic-forms/fields/cinchy-form-datetime.directive.ts, src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts, src/app/dynamic-forms/fields/cinchy-form-multichoice.directive.ts, src/app/dynamic-forms/fields/cinchy-form-number.directive.ts, src/app/dynamic-forms/fields/cinchy-form-textarea.directive.ts, src/app/dynamic-forms/fields/cinchy-form-textbox.directive.ts, src/app/dynamic-forms/style/style.scss, src/global-styles/variables.scss, src/styles.scss
- committing changes for tooltip
=> CIN-01138: Improved display of field metadata

src/app/dynamic-forms/fields/cinchy-form-datetime.directive.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts
- fixed dropdown bug for CIN-00441: Form drop down menus display single and multi values correctly when focus is lost
=> CIN-00441 : Form drop down menus display single and multi values correctly when focus is lost

src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts
dropdown blank and hierarchy issue resolved.
=> EXP-00598: Tooltip Icon and tooltip is not properly showing on hierarchy column and multi choice column.

Dockerfile
Reverts cinchy-co/meta-forms-app-experience#90
=> Revert "updated nginx base"

src/app/dynamic-forms/service/print/print.service.ts
… missing when the parent form is exported to PDF
=> EXP-00646:  Fields that contain URLs from a child form are missing when the parent form is exported to PDF

package.json, src/healthcheck
=> Update version to v5.3.2

src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/fields/cinchy-form-link.directive.ts, src/app/dynamic-forms/models/cinchy-column.model.ts, src/app/dynamic-forms/service/form-helper/form-helper.service.ts, src/app/models/form-field-metadata.model.ts, src/styles.scss
- committed domain name and text-width changes for form tooltip
=> CIN-02378: Tooltips don't show the table name/link

src/app/dynamic-forms/fields/cinchy-child-form-table.directive.ts, src/app/dynamic-forms/fields/cinchy-child-form.directive.ts
- committing changes for child form link which is having wrong cinchy id .
=> CIN-02576: Links to files not valid when displayed in edit child form modal

src/app/dynamic-forms/fields/cinchy-form-textbox.directive.ts
committing changes for image URL bug
=> CIN-01470: Images incorrectly include the URL as a label when setting the "Data Type Format" to ImageURL

src/app/dynamic-forms/enums/imageurl-type.ts, src/app/dynamic-forms/fields/textbox/textbox.component.html, src/app/dynamic-forms/fields/textbox/textbox.component.ts
For ImageUrl fields, the rendered image was not adhering to the expected size based on the dataFormatType. This has been corrected.
=> Image size fix

.gitignore, src/app/dynamic-forms/fields/cinchy-form-link-multichoice.ts, src/app/dynamic-forms/models/cinchy-form-field.model.ts, src/app/dynamic-forms/models/cinchy-form.model.ts
Corrected incorrect parsing logic when saving the field's value and added null checks in the logic for saving the whole form.
This version of the PR is targeting v5.3.3 specifically.
=> [v5.3.3] CIN-03643: save fails when removing and then adding images on a link-multichoice field

src/app/core/sidenav/sidenav.component.ts, src/app/dynamic-forms/cinchy-dynamic-forms.component.ts
- committing changes for Null check
=> CIN-04688: Child forms not displayed as configured

src/app/dynamic-forms/service/print/print.service.ts
CIN-06324 - Made the font-size of links in exported PDFs the same size as other text
=> CIN-06324 - Made the font-size of links in exported PDFs the same size as other text 

src/app/app.component.ts, src/app/dynamic-forms/cinchy-dynamic-forms.component.ts
CIN-06064 - Removed URL param logic during login that is now handled by the Angular SDK
=> CIN-06064 - Removed URL param logic during login that is now handled by the Angular SDK

src/app/core/sidenav/sidenav.component.html, src/app/core/sidenav/sidenav.component.ts, src/app/dynamic-forms/cinchy-dynamic-forms.component.html, src/app/dynamic-forms/cinchy-dynamic-forms.component.ts, src/app/dynamic-forms/style/style.scss, src/global-styles/variables.scss, src/styles.scss
- Move 'create new record', 'duplicate record', 'export as pdf' and 'back to table view' into a menu. 
- Add functionality to copy url.
=> CIN-06144: Move all actions into one menu and add options to copy record link

src/app/dynamic-forms/models/cinchy-form.model.ts
*Summary of the changes and the related issue*: Added a consistent formatting step to the query generation in cases where a date field has been updated.
*Relevant motivation and context*: Some users were experiencing an issue where the month and day were being switched due to their locale, which is at best incorrect and at worst a component crash when the date was anything over 12. These changes ensure that the server and the client are working with the same information, and that the user selections persist as they selected them.
*Affected components and dependencies*:  Form class (`generateSaveQuery` and `generateSaveForChildQuery` functions)
*Related pull requests*: N/A
[ ] Refactor (this change should have no impact on existing functionality)
[x] Bug fix (non-breaking change which …
=> CIN-01910: Issues with Dates

src/app/dynamic-forms/models/cinchy-form.model.ts, src/app/dynamic-forms/service/print/print.service.ts
Fixing defect in [CIN-01910](https://github.com/cinchy-co/meta-forms-app-experience/pull/176) where dates in exported PDFs did not adhere to the displayFormat designated by the user.
=> CIN-01910: defect resolution

src/app/dynamic-forms/fields/link-multichoice/link-multichoice.component.ts, src/app/dynamic-forms/fields/link/link.component.ts, src/assets/config/config.json
Recreating the display column filter fix for 5.6.3
=> CIN-08262: Filter fix

src/app/dynamic-forms/cinchy-dynamic-forms.component.ts, src/app/dynamic-forms/models/cinchy-form.model.ts, src/app/dynamic-forms/service/child-form/child-form.service.ts
The following fixes concern the child from only.
- When linked column is updated, change the display column value to "-".
- Fix issue with loading display column for multi-select linked column.
=> CIN-08375: Update display column values to "-" if linked column has changed

src/app/constants/regex-column-name-in-error.constant.ts, src/app/dynamic-forms/fields/link-multichoice/link-multichoice.component.html, src/app/dynamic-forms/fields/link-multichoice/link-multichoice.component.ts, src/app/dynamic-forms/fields/link/link.component.ts, src/app/dynamic-forms/service/cinchy-dropdown-dataset/cinchy-dropdown-dataset.service.ts, src/app/services/cinchy-query.service.ts, src/app/shared/search-dropdown/search-dropdown.component.ts
https://github.com/cinchy-co/meta-forms-app-experience/pull/239 (Fix to update url and dropdown selection on search record change)
https://github.com/cinchy-co/meta-forms-app-experience/pull/238 (Link dropdown with filter should work for new records)
https://github.com/cinchy-co/meta-forms-app-experience/pull/233 (Ignore deleted display columns when rendering a form)
https://github.com/cinchy-co/meta-forms-app-experience/pull/243 (Fix executeCQL loop - Regression fix for PR #233)
=> CIN-10762: v5.12.0 consolidation

src/app/services/cinchy-query.service.ts
=> CIN-10998: Fix invalid trim function in Forms
